set nocount on;

print char(10) + 'Test data:';

print 'Adding generic test users'
	insert dbo.[User] (Name, Email, SimpleHash)
	values
		('Robert Koritnik', 'r@k.com', -198892813); -- password: koji
	declare @id int = scope_identity();

print 'Adding few test posts'
	insert dbo.Post (Title, Content, AuthorId)
	values
		(
		'Sega Mega Drive: why retro consoles are about more than nostalgia',
		'<p class="intro">A new version of the classic1988 games console is selling well this year, apparently, but the appeal of this system goes deeper than reminiscence.</p><p>Every year at about this time, newspapers love to identify the biggest-selling Christmas presents – those sudden surprise hits that have desperate shoppers combing internet stores for hours or simply fighting each other in Toys R Us.	</p><p>This year, among other candidates, is a £40 wireless version of the Sega Mega Drive, the classic 1988 games console, famous for Sonic the Hedgehog. According to Argos, sales of the retro gadget, which includes 80 built-in games (although only 40 are Mega Drive classics, the rest are generic mini-games like solitaire) and a cartridge port so you can use any original game carts you have lying around, have risen by 400% this month. While we’re all supposed to be saving up for cutting-edge machines like the PlayStation 4 and Xbox One, some families will be gathered around a very different audio-visual experience come 25 December.</p>',
		@id),
		(
		'Google offers legal support to some YouTube users in copyright battles',
		'<p class="intro">The tech company pledges to cover legal costs for handful of videos that it claims represent clear fair use despite being issued DMCA takedown notices</p><p>Google is stepping up its defense of YouTube users who find themselves on the wrong side of a copyright claim, the tech company said on Thursday.</p><p>After a series of skirmishes with established media and others the company said it was “offering legal support to a handful of videos that we believe represent clear fair uses which have been subject to DMCA [Digital Millennium Copyright Act] takedowns”.</p><p>Google’s move comes after privacy group Electronic Frontier Foundation successfully defended Stephanie Lenz, a mother whose 29-second video of her son dancing to Prince’s Let’s Go Crazy had been removed from YouTube after Universal Music issued a DMCA notice ordering it to be taken down.</p><p>“With approval of the video creators, we’ll keep the videos live on YouTube in the US, feature them in the YouTube Copyright Center as strong examples of fair use, and cover the cost of any copyright lawsuits brought against them,” Fred von Lohmann, Google’s copyright legal director, wrote on the Google blog.</p><p>Von Lohmann admitted that Google was not going to shoulder the court costs of every user on its site – not even every user with a solid case – but he said the company did want to demystify the process by which users could wield the law as effectively as entertainment companies. “We’re doing this because we recognize that creators can be intimidated by the DMCA’s counter notification process, and the potential for litigation that comes with it,” he wrote.</p>',
		@id),
		(
		'Facebook tests ''break-up'' tools',
		'<p class="intro">Breaking up is hard to do - especially on Facebook.</p><p>There''s no feeling quite like the tightening of the stomach you get when you accidentally stumble across an old post involving you and a former loved one in happier times. It''s even more brutal when you notice that person''s surname has since changed. Anyway. The world''s biggest social network <a href="http://newsroom.fb.com/news/2015/11/improving-the-experience-when-relationships-end/">has just announced that it is trialling new tools</a> to make it less painful when handling a relationship gone sour.</p><p>Right now, if you decide you don''t want to be reminded of a certain someone''s existence on planet Earth, you would need to unfriend or block them. The problem is that they will most likely find out you''ve done that, which isn''t exactly ideal - nothing says "playing it cool" like blocking someone on Facebook.</p><p>Relationships on Facebook are a big deal - a judge in New York said using Facebook to send a divorce summons was completely legal.</p><p>Facebook''s new break-up tool is about altering what an ex can see, but without them knowing you''ve done anything. The tool allows people to:</p><ul><li>See less of a former partner''s name and profile picture around Facebook without having to unfriend or block them. Their posts won''t show up in News Feed and their name won''t be suggested when people write a new message or tag friends in photos.</li><li>Limit the photos, videos or status updates that a former partner will see.</li><li>Edit who can see their past posts with a former partner and untag themselves from posts with that person.</li></ul><p>When Facebook first launched on college campuses, it was essentially a database of relationship statuses. A kind of <a href="https://en.wikipedia.org/wiki/Stop_light_party">digital traffic light party</a> that saved everyone a lot of time.</p>',
		@id),
		(
		'People have been waiting for the tech bubble to collapse since 2007',
		'<p class="intro">When an initial public offering revealed that the payment technology company Square was worth <a href="http://www.theverge.com/2015/11/19/9757210/square-ipo-valuation-down-round-tech-bubble">less than people thought</a> this week, it intensified discussion about whether Silicon Valley is in the midst of a <a href="http://www.vox.com/2015/10/27/9617996/silicon-valley-boom-fragile">second technology bubble</a> that''s about to pop. And it reminded me of this funny viral video that made the rounds online in December 2007, called "Here Comes Another Bubble."</p><p>It''s a good reminder that people started worrying about a second technology bubble almost immediately after the first one popped. It''s also a fun time capsule of internet culture circa 2007. Back then, MySpace was still considered relevant, and blogs dominated the technology conversation more than they do today.</p><p>But the really striking thing about the video is the examples the video''s creators chose to illustrate the alleged Silicon Valley bubble. They noted that Facebook was worth $15 billion, almost as much as Ford Motor Company. YouTube had recently been purchased for $1.65 billion, and Skype for $2.6 billion.</p><h3>People thought there was a technology bubble in 2007, but there wasn''t</h3><p>Today, of course, Facebook is worth about $300 billion — 20 times more than in 2007. Microsoft bought Skype for $8.5 billion in 2011 — more than triple what eBay paid for it in 2005. YouTube is still a subsidiary of Google, so we don''t know its exact value, but it''s a safe bet that it''s worth a lot more than $1.65 billion today.</p><p>To be fair, the other two companies mentioned in the video — an RSS feed company called Feedburner at $100 million and an advertising company called aQuantive at $6 billion — did turn out to be hugely overvalued. But it''s clear that in 2007 a lot of people were hugely underestimating how valuable high-profile internet companies would become.</p><p>Obviously, it would be ridiculous to say this proves there''s no technology bubble today. But it does illustrate something important about the way bubble conversations happen. <em>Eventually</em>, there''s going to be a broad downturn in technology stocks, and whoever said there was a bubble right beforehand will look prescient. But there are also times when people say there''s a bubble and then company values keep going up. And rather than treating that as a sign that there wasn''t a bubble, people interpret it as a sign that the bubble has gotten even bigger.</p>',
		@id);

set nocount off;